### PR TITLE
remove redirection to another page & add copy link in home page

### PR DESCRIPTION
**Pull request by ThejasKiranPS**
closes: #50 
1. disabled redirection to display page
2. url is copied when clicking share button
3. added copy button in home page

### CODE REVIEW

**Comment by ThejasKiranPS** [comment]
Any changes needed?

**Comment by ajomadlabs** [comment]
@ThejasKiranPS Great work 💯 

Few pointers that I would like to put it down

- When the editor is empty and the user presses the copy button, we need to give an error conveying that the editor is empty or there is not content to be copied.
- When the editor is empty, clicking on the share button should also throw an error.
- The input box in the alert box which pops up on clicking the share button should be read-only. The users should not be able to edit anything inside the input box.

cc: @alceil

**Comment by ThejasKiranPS** [comment]
I think someone's already working on empty editor checks; issue 44

**Comment by ThejasKiranPS** [comment]
> We will merge it but there is another issue to be taken care of we will raise an issue about it soon.

need any help?

**Comment by ThejasKiranPS** [comment]
> It's related to link sharing bro. if you can help it will be really amazing!

Yess I'm interested

**Comment by ThejasKiranPS** [comment]
Can you show the working code which is deployed in heroku
And the api urls to retrieve data

> Like when a link is generated try opening it through the browser it will show a page not found error. Works perfectly in Heroku but in Netlify problem exists. try opening this link you will understand whats the problem https://justpasteit.netlify.app/616efeb901bdda00153fa54a

**Comment by alceil** [comment]
Woah amazing work🤩

**Comment by ThejasKiranPS** [comment]
since display on netlify is working should I bring back the share page and redirect to share page hosted on netlify itself?

**Pull request closed without merging**
