### PR TITLE
[Issue #6] Added highlight support

### LINKED ISSUE #6: 💡 Syntax highlight support
There seems to be two ways to do this:

1. Implement a complete online editor: https://github.com/quilljs/quill or https://github.com/ajaxorg/ace or  https://github.com/facebook/draft-js or https://github.com/codemirror/codemirror.next/
2. Use a library: https://github.com/highlightjs/highlight.js

> Don't know how to implement them. I'm sorry, I'm not familiar with react yet.

### PR DESCRIPTION
**Pull request by DownloadableFox**
It took sometime to actually finish this, but I think it ended up pretty nicely.

Fix #6

### CODE REVIEW

**Comment by ajomadlabs** [comment]
@DownloadableFox Great Work 💯 

Couple of suggestions which could also be addressed in this PR 
- The highlighting section in light mode can be improved.
- Opening the shared snippet doesn't give the code highlighted UI

For more reference you can check these screenshots

Screenshot 2021-10-16 at 9 16 56 AM

Screenshot 2021-10-16 at 9 21 24 AM

**Comment by DownloadableFox** [comment]
Thanks for telling me. You're right. I'll fix this is no time.

**Comment by alceil** [comment]
Ya its really amazing 🤩

**Comment by DownloadableFox** [comment]
Done!

Highlight support added + minor fixes to UI in dark/light mode + working on share page.

Here are some pictures in light and dark mode.
image
image
image
image

**Pull request merged**
