### PR TITLE
update copying url to netlify deploy

### PR DESCRIPTION
**Pull request by ThejasKiranPS**

### CODE REVIEW

**Comment by DownloadableFox** [comment]
Hello!

I just thought that maybe it could be better if we copied the URL dynamically instead of having it hardcoded. Every time the domain changes we'll need to change the code to fit for the domain change, and that's really unnecessary. Another thing to take in mind is, while developing, most of us rather run the code locally to see the changes directly, accessing the site through one local port (default 3000).

While doing this and clicking the button, you would copy `justpastit.netify.com/{id}` Instead of something like `127.0.0.1:3000/{id}`, and this could be bad, as Netify wouldn't have the version you're editing at the moment so by checking that link you're probably missing features.

I would suggest replacing the URL string with `window.location.hostname`. Or, an alternative more React-like way would be using *react-router-dom*.

An example of *react-router-dom* could be something like this:
`import { useLocation } from 'react-router-dom';

const getHostname= () => {
  const location = useLocation();
  return location.hostname;
}`

By doing that we would get the current hostname where the website is hosted and wouldn't nice to replace the string again. Good work! :D

**Comment by ThejasKiranPS** [comment]
Thanks for the great suggestion @DownloadableFox 
localhost uses http and netlify uses https so that would need an additional step while generating url from  hostname

What I did here is generating url from the current url. 
just ```window.location.href``` is enough but in future there may be a case where we develop an additional page or so which will add something like /share or /copy after /id (like ```https://justpasteit.netlify.app/6170ddb975fd0200158322f8/copy)```
To avoid copying that I have split the url till the 3rd occurrence of ```'/'``` and append ```ID``` to that.

is this unnecessary complexity? give your suggestions we can do anyway you like @alceil

**Comment by ajomadlabs** [comment]
@ThejasKiranPS For this I think we could go with the approach that @DownloadableFox has proposed. Making the url's dynamic would make it hassle free. I don't think this will cause any problem in local but need to confirm.

**Comment by DownloadableFox** [comment]
@ThejasKiranPS You could try using both `window.location.protocol` & `window.location.hostname`.

**Comment by ThejasKiranPS** [comment]
> @ThejasKiranPS You could try using both `window.location.protocol` & `window.location.hostname` instead of href.
> 
> Example:
> 
> ```js
> const ShareURL = `${window.location.protocol}//${window.location.hostname}/${id}`;
> ```
> 
> or
> 
> ```js
> import { useLocation } from 'react-router-dom';
> 
> const getShareLink = (id) => {
>   const location = useLocation();
>   return `${location.protocol}//${location.hostname}/${id}`;
> }
> ```
> 
> This will remove the protocol problem and would make it easier if there was a URI path change. With this, we can skip the fancy string manipulation that as you said, added extra complexity.

Done... Thanks for these tips

**Pull request merged**
